### PR TITLE
View/edit account details page + account deletion

### PR DESCRIPTION
**Pull request by miloaisdino**
This page displays the account details according to the spec
Screenshot 2023-12-19 at 2 14 47 AM

### CODE REVIEW

**Comment by miloaisdino** [comment]
Account deletion now working
Screenshot 2023-12-20 at 11 38 46 PM
Screenshot 2023-12-20 at 11 40 14 PM

Screenshot 2023-12-20 at 11 39 33 PM
Screenshot 2023-12-20 at 11 39 48 PM

**Comment by miloaisdino** [comment]
Add account update functionality
Screenshot 2023-12-21 at 2 26 25 AM
Screenshot 2023-12-21 at 2 26 45 AM
Screenshot 2023-12-21 at 2 27 03 AM
Screenshot 2023-12-21 at 2 27 29 AM

**Comment by sltsheryl** [comment]
or instead of making the fields mandatory, if its blank could just let the field remain the same as previous

**Comment by miloaisdino** [comment]
Noted and will add the optional functionality as requested.
Fyi dob is currently null on user creation. 
Would you like to change this logic? 
Thanks

**Comment by miloaisdino** [comment]
For clarification, wrt the user spec, if user does not edit the particular field eg “name”, it will remain unchanged. 
Please let me know if you like to change this accordingly.

**Comment by sltsheryl** [comment]
> Noted and will add the optional functionality as requested. Fyi dob is currently null on user creation. Would you like to change this logic? Thanks

I think it’s fine to leave the dob null upon creation. what I was referring to is if I tries to edit the user details in the edit form (it doesn’t indicate any of the fields are mandatory) while leaving the date empty, it results in error. I think we shd let users be able to edit their profile even without filling in the dob (or shd we enforce this? what do you think)

**Comment by sltsheryl** [comment]
> For clarification, wrt the user spec, if user does not edit the particular field eg “name”, it will remain unchanged. Please let me know if you like to change this accordingly.

Yea this behaviour sounds ok 👍

**Comment by miloaisdino** [comment]
Thats odd, it doesnt result in error on my end. I will check again

**Comment by miloaisdino** [comment]
Yup I agree its a good idea to enforce dob upon user edit. Will commit accordingly

**Comment by sltsheryl** [comment]
> Thats odd, it doesnt result in error on my end. Could be an issue with the db schema version. I will check again

Screenshot 2024-01-05 at 10 11 18 AM

Screenshot 2024-01-05 at 10 11 29 AM

### To replicate:
Sign up
Try editing without filling in the dob field (just the name field)
Enter otp

**Comment by sltsheryl** [comment]
To create a new PR for the remaining changes @miloaisdino

**Pull request merged**
