### PR TITLE
Update schema.prisma for backend game

### PR DESCRIPTION
**Pull request by yunpeng1234**
#37 

Not sure if this is the ideal way to put game answers.

Answer table should just be a collection of answers that is constant and should not be linked to game states.
Feel free to suggest something else as it is similar to sorting game as well.

Have not prisma push to the backend yet

### CODE REVIEW

**Comment by yunpeng1234** [comment]
Have added new type of schema to have fix permutation of game.
image
Schema targets this game, not sure if this is matching or sorting. API in progress

**Comment by kevinchua6** [comment]
Looks ok, rmb to update Postman with your new endpoints as well (so it's easier for me to test also) https://github.com/Project-Juniors-Club/jc-app/tree/main/docs

**Review by MorningLit — DISMISSED** [review]

**Comment by yunpeng1234** [comment]
Dont merge yet, Postman has yet to be updated

**Comment by weixin-tan** [comment]
Merge main into this first for new schema changes.

**Pull request closed without merging**
